---
title: "NHIS Recode 2022"
author: "Jose Rico"
date: "2024-08-13"
output: html_document
---

```{r setup, include=FALSE}
library(ipumsr)
library(tidyverse)
library(jsonlite)
```

Load data

```{r cars}
ddi <- read_ipums_ddi("nhis_00001.xml")
data_2022 <- read_ipums_micro(ddi)
```


## 2022 data (prefer variables for alcohol and marriage cohab better)

```{r}
data_2022_recode <- data %>% 
  select(AGE,SEX, SEXORIEN, MARSTCOHAB, RACENEW, HISPETH, HISPRACE, YRSINUSG, USBORN, CITIZEN, EDUC, SCHOOLNOW, EMPSTAT, HOURSWRK, EMPHI, EMPFT, OWNERSHIP, HOUYRSLIV, HEALTH, HEIGHT, WEIGHT, BMICALC, BMICAT, DELAYCOST,  MHRX, YDELAYMENTAL, PREMEDYR, ADDEV, ADHDNOW, CANCEREV, CHOLHIGHEV , CHOLHIGHYR, DEPRESSEV, LEARNDEV , STROKEV , ALC5UPEVYR, ALC5UPOCC30D, ALCSTAT1, PA18AERSTR, HRSLEEP, SLEEPRESTFRQ , SLEEPFALLFRQ , SLEEPSTAYFRQ  , SLEEPMEDFRQ, DSOCIALP  , WORFREQ , WORRX , WORFEELEVL, GADANX , DEPFREQ , DEPRX, DEPFEELEVL  , CVDDIAG , CVDTESTRSLT , CVDSYMP   ) %>% 
  mutate(AGE = as.numeric(AGE)) %>% 
  mutate(SEX = as.factor(SEX)) %>% 
  mutate(SEXORIEN = as.factor(SEXORIEN)) %>% 
  mutate(RACENEW = as.factor(RACENEW)) %>% 
  mutate(MARSTCOHAB = as.factor(MARSTCOHAB)) %>% 
  mutate(HISPETH = as.factor(HISPETH)) %>% 
  mutate(HISPRACE = as.factor(HISPRACE)) %>% 
  mutate(YRSINUSG = as.factor(YRSINUSG)) %>% 
  mutate(USBORN = as.factor(USBORN)) %>% 
  mutate(CITIZEN = as.factor(CITIZEN)) %>% 
  mutate(EDUC = as.factor(EDUC)) %>% 
  mutate(SCHOOLNOW = as.factor(SCHOOLNOW)) %>% 
  mutate(EMPSTAT  = as.factor(EMPSTAT )) %>% 
  mutate(HOURSWRK = as.numeric(HOURSWRK)) %>% 
  mutate(EMPHI  = as.factor(EMPHI)) %>%
  mutate(EMPFT  = as.factor(EMPFT)) %>%
  mutate(OWNERSHIP  = as.factor(OWNERSHIP)) %>%
  mutate(HOUYRSLIV  = as.factor(HOUYRSLIV)) %>%
  mutate(HEALTH  = as.factor(HEALTH)) %>%
  mutate(HEIGHT = as.numeric(HEIGHT)) %>%
  mutate(WEIGHT = as.numeric(WEIGHT)) %>%
  mutate(BMICALC = as.numeric(BMICALC)) %>%
   mutate(BMICAT  = as.factor(BMICAT)) %>%
  mutate(DELAYCOST  = as.factor(DELAYCOST)) %>%
  mutate(MHRX  = as.factor(MHRX)) %>%
  mutate(YDELAYMENTAL  = as.factor(YDELAYMENTAL)) %>%
  mutate(PREMEDYR  = as.factor(PREMEDYR)) %>%
  mutate(ADDEV  = as.factor(ADDEV)) %>%
  mutate(ADHDNOW  = as.factor(ADHDNOW)) %>%
  mutate(CANCEREV    = as.factor(CANCEREV  )) %>%
  mutate(CHOLHIGHEV  = as.factor(CHOLHIGHEV)) %>%
  mutate(CHOLHIGHYR   = as.factor(CHOLHIGHYR )) %>%
  mutate(DEPRESSEV   = as.factor(DEPRESSEV )) %>%
  mutate(LEARNDEV   = as.factor(LEARNDEV )) %>%
  mutate(STROKEV    = as.factor(STROKEV  )) %>%
  mutate(ALC5UPEVYR    = as.factor(ALC5UPEVYR  )) %>%
  mutate(ALC5UPOCC30D = as.numeric(ALC5UPOCC30D)) %>%
  mutate(ALCSTAT1     = as.factor(ALCSTAT1   )) %>%
  mutate(PA18AERSTR   = as.factor(PA18AERSTR  )) %>%
  mutate(HRSLEEP = as.numeric(HRSLEEP)) %>%
  mutate(SLEEPRESTFRQ   = as.factor(SLEEPRESTFRQ )) %>%
  mutate(SLEEPFALLFRQ   = as.factor(SLEEPFALLFRQ )) %>%
  mutate(SLEEPSTAYFRQ    = as.factor(SLEEPSTAYFRQ  )) %>%
  mutate(SLEEPMEDFRQ     = as.factor(SLEEPMEDFRQ   )) %>%
  
  mutate(DSOCIALP     = as.factor(DSOCIALP   )) %>%
  mutate(WORFREQ   = as.factor(WORFREQ )) %>%
  mutate(WORRX    = as.factor(WORRX  )) %>%
  mutate(WORFEELEVL    = as.factor(WORFEELEVL   )) %>%
  mutate(GADANX  = as.factor(GADANX )) %>%
  mutate(DEPFREQ   = as.factor(DEPFREQ)) %>%
  mutate(DEPRX     = as.factor(DEPRX  )) %>%
  mutate(DEPFEELEVL     = as.factor(DEPFEELEVL   )) %>%
  mutate(CVDDIAG   = as.factor(CVDDIAG  )) %>%
  mutate(CVDTESTRSLT   = as.factor(CVDTESTRSLT )) %>%
  mutate(CVDSYMP     = as.factor(CVDSYMP  )) %>%
  mutate(SEX = recode_factor(SEX,
                             "1"="Male",
                             "2"="Female",
                             "7"="Unknown",
                             "8"="Unknown",
                             "9"="Unknown",
                                .ordered=T)) %>%
  mutate(SEXORIEN = recode_factor(SEXORIEN,
                             "0"="NIU",
                             "1"="Lesbian or Gay",
                             "2"="Straight",
                             "3"="Bisexual",
                             "4"="Something else",
                             "6"="Unknown",
                             "7"="Unknown",
                             "8"="Unknown",
                                .ordered=T)) %>%
  mutate(MARSTCOHAB = recode_factor(MARSTCOHAB,
                             "0"="NIU",
                             "1"="Married, spouse present",
                             "2"="Married, spouse absent",
                             "3"="Married, spouse in household unknown",
                             "4"="Separated",
                             "5"="Divorced",
                             "6"="Widowed",
                             "7"="Living with partner",
                             "8"="Never Married",
                             "9"="Unknown",
                                .ordered=T)) %>%
  mutate(RACENEW = recode_factor(RACENEW,
                             "100"="White Only",
                             "200"="Black/African American only",
                             "300"="American Indian only",
                             "400"="Asian Only",
                             "500"="Other Race and Multiple Race",
                             "510"="Other Race and Multiple Race",
                             "520"="Other Race",
                             "530"="Race Group Not Releasable",
                             "540"="Multiple Race",
                             "541"="Multiple Race",
                             "542"="American Indian and Any Other Race",
                             "997"="Unknown",
                             "998"="Unknown",
                             "999"="Unknown",
                                .ordered=T)) %>% 
    mutate(HISPETH = recode_factor(HISPETH,
                             "10"="Not Hispanic",
                             "20"="Mexican",
                             "21"="Mexican",
                             "22"="Mexican",
                             "23"="Mexican",
                             "24"="Mexican",
                             "30"="Puerto Rican",
                             "40"="Cuban",
                             "50"="Dominican (Republic)",
                             "60"="Other Hispanic",
                             "61"="Central or South American",
                             "62"="Other Hispanic or not specified",
                             "63"="Other Hispanic or not specified",
                             "64"="Other Hispanic or not specified",
                             "65"="Other Hispanic or not specified",
                             "66"="Other Hispanic or not specified",
                             "67"="Other Hispanic or not specified",
                             "70"="Other Hispanic or not specified",
                             "90"="Unknown",
                             "91"="Unknown",
                             "92"="Unknown",
                             "93"="Unknown",
                             "99"="NIU",
                                .ordered=T)) %>% 
    mutate(HISPRACE = recode_factor(HISPRACE,
                             "1"="Hispanic",       
                             "2"="White (NH)",
                             "3"="Black/African American (NH)",
                             "5"="American Indian (NH)",
                             "4"="Asian (NH)",
                             "6"="American Indian and Any Other Race (NH)",
                             "7"="Other Single and Multiple Race (NH)",
                             "97"="Unknown",
                             "98"="Unknown",
                             "99"="Unknown",
                             .ordered=T)) %>% 
  mutate(YRSINUSG = recode_factor(YRSINUSG,
                             "1"="Less than 1",
                             "2"="1 year to less than 5 years",
                             "3"="5 years to less than 10",
                             "4"="10 years to less than 15 years",
                             "5"="15 years or more",
                             "7"="Unknown",
                             "8"="Unknown",
                             "9"="Unknown",
                             "0"="NIU",
                             .ordered=T)) %>% 
  mutate(USBORN = recode_factor(USBORN,
                             "10"="No",
                             "11"="No, US Territory",
                             "12"="No",
                             "20"="Yes",
                             "96"="NIU",
                             "97"="Unknown",
                             "98"="Unknown",
                             "99"="Unknown",
                             .ordered=T)) %>% 
  mutate(CITIZEN = recode_factor(CITIZEN,
                             "1"="Not a US Citizen",
                             "2"="Yes, US Citizen",
                             "7"="Unknown",
                             "8"="Unknown",
                             "9"="Unknown",
                             .ordered=T)) %>% 
  mutate(EDUC = recode_factor(EDUC,         
                       "100"="no high school diploma",
                       "101"="no high school diploma",
                       "102"="no high school diploma",
                       "103"="no high school diploma",
                       "104"="no high school diploma",
                       "105"="no high school diploma",
                       "106"="no high school diploma",
                       "107"="no high school diploma",
                       "108"="no high school diploma",
                       "109"="no high school diploma",
                       "110"="no high school diploma",
                       "111"="no high school diploma",
                       "112"="no high school diploma",
                       "113"="no high school diploma",
                       "114"="no high school diploma",
                       "115"="no high school diploma",
                       "116"="no high school diploma",
                       "200"= "High school diploma or GED",
                       "201"= "High school diploma or GED",
                       "202"= "High school diploma or GED",
                       "300"="Some college",
                       "301"="Some college",
                       "302"="VoTech degree",
                       "303"="AA degree",
                       "400"="Bachelor's degree",
                       "500"="Advanced degree",
                       "501"="Master's degree",
                       "502"="Professional",
                       "503"="Doctoral degree", 
                       "504"="Other degree",
                       "505"="Professional School or Doctoral degree",
                       "996"= "Unknown",
                       "997"= "Unknown",
                       "998"= "Unknown",
                       "999" = "Unknown",
                       .ordered=T)) %>% 
  mutate(SCHOOLNOW  = recode_factor(SCHOOLNOW ,
                             "0"="NIU",
                             "1"="Not in school",
                             "2"="Yes, in school",
                             "7"="Unknown",
                             "8"="Unknown",
                             "9"="Unknown",
                             .ordered=T)) %>%
   mutate(EMPSTAT = recode_factor(EMPSTAT,         
                       "000"="NIU",
                       "100"="Employed",
                       "110"="Employed",
                       "111"="Employed",
                       "112"="Employed w/out pay",
                       "120"="Employed",
                       "121"="Employed",
                       "200"="Unemployed",
                       "210"="Unemployed",
                       "211"="Unemployed",
                       "212"="Unemployed",
                       "213"="Unemployed",
                       "214"="Unemployed",
                       "215"="Unemployed",
                       "216"="Unemployed",
                       "217"="Unemployed",
                       "220"="Not in labor force",
                       "900"= "Unknown",
                       "997"= "Unknown",
                       "998"= "Unknown",
                       "999" = "Unknown",
                        .ordered=T)) %>% 
  mutate(EMPHI = recode_factor(EMPHI,
                             "0"="NIU",
                             "1"="No",
                             "2"="Yes",
                             "7"="Unknown",
                             "8"="Unknown",
                             "9"="Unknown",
                                .ordered=T)) %>%
  mutate(EMPFT = recode_factor(EMPFT,
                             "0"="NIU",
                             "1"="No",
                             "2"="Yes",
                             "7"="Unknown",
                             "8"="Unknown",
                             "9"="Unknown",
                                .ordered=T)) %>%
    mutate(OWNERSHIP = recode_factor(OWNERSHIP,
                             "00"="NIU",
                             "10"="Owned",
                             "11"="Owned",
                             "12"="Owned",
                             "20"="Rented",
                             "30"="Other",
                             "40"="Rent Free",
                             "97"="Unknown",
                             "98"="Unknown",
                             "99"="Unknown",
                             .ordered=T)) %>% 
    mutate(HOUYRSLIV  = recode_factor(HOUYRSLIV ,
                             "0"="NIU",
                             "1"="less than 1 year",
                             "2"="1 to 3 years",
                             "3"="4 to 10 years",
                             "4"="11-20 years",
                             "5"="More 20 years",
                             "7"="Unknown",
                             "8"="Unknown",
                             "9"="Unknown",
                             .ordered=T)) %>%
  mutate(HEALTH  = recode_factor(HEALTH ,
                             "1"="Excellent",
                             "2"="Very Good",
                             "3"="Good",
                             "4"="Fair",
                             "5"="Poor",
                             "7"="Unknown",
                             "8"="Unknown",
                             "9"="Unknown",
                             .ordered=T)) %>% 
  mutate(BMICAT  = recode_factor(BMICAT ,
                             "0"="NIU",    
                             "1"="Underweight (BMI < 18.5)",
                             "2"="Normal weight (BMI >= 18.5 & BMI < 25)",
                             "3"="Overweight (BMI >= 25  & BMI < 30)",
                             "4"="Obese (BMI 30+)",
                             "9"="Unknown",
                             .ordered=T)) %>% 
  mutate(DELAYCOST  = recode_factor(DELAYCOST ,
                             "0"="NIU",
                             "1"="No",
                             "2"="Yes",
                             "7"="Unknown",
                             "8"="Unknown",
                             "9"="Unknown",
                             .ordered=T)) %>%
   mutate(MHRX  = recode_factor(MHRX ,
                             "0"="NIU",
                             "1"="No",
                             "2"="Yes",
                             "7"="Unknown",
                             "8"="Unknown",
                             "9"="Unknown",
                             .ordered=T)) %>%
  mutate(YDELAYMENTAL   = recode_factor(YDELAYMENTAL  ,
                             "0"="NIU",
                             "1"="No",
                             "2"="Yes",
                             "7"="Unknown",
                             "8"="Unknown",
                             "9"="Unknown",
                             .ordered=T)) %>%
  mutate(PREMEDYR     = recode_factor(PREMEDYR    ,
                             "0"="NIU",
                             "1"="No",
                             "2"="Yes",
                             "7"="Unknown",
                             "8"="Unknown",
                             "9"="Unknown",
                             .ordered=T)) %>%
    mutate(ADDEV     = recode_factor(ADDEV   ,
                             "0"="NIU",
                             "1"="No",
                             "2"="Yes",
                             "7"="Unknown",
                             "8"="Unknown",
                             "9"="Unknown",
                             .ordered=T)) %>%
  mutate(ADHDNOW     = recode_factor(ADHDNOW   ,
                             "0"="NIU",
                             "1"="No",
                             "2"="Yes",
                             "7"="Unknown",
                             "8"="Unknown",
                             "9"="Unknown",
                             .ordered=T)) %>%
  mutate(CANCEREV  = recode_factor(CANCEREV ,
                             "0"="NIU",
                             "1"="No",
                             "2"="Yes",
                             "7"="Unknown",
                             "8"="Unknown",
                             "9"="Unknown",
                             .ordered=T)) %>%
   mutate(CHOLHIGHEV  = recode_factor(CHOLHIGHEV ,
                             "0"="NIU",
                             "1"="No",
                             "2"="Yes",
                             "7"="Unknown",
                             "8"="Unknown",
                             "9"="Unknown",
                             .ordered=T)) %>%
  mutate(CHOLHIGHYR   = recode_factor(CHOLHIGHYR  ,
                             "0"="NIU",
                             "1"="No",
                             "2"="Yes",
                             "7"="Unknown",
                             "8"="Unknown",
                             "9"="Unknown",
                             .ordered=T)) %>%
  mutate(DEPRESSEV     = recode_factor(DEPRESSEV    ,
                             "0"="NIU",
                             "1"="No",
                             "2"="Yes",
                             "7"="Unknown",
                             "8"="Unknown",
                             "9"="Unknown",
                             .ordered=T)) %>%
    mutate(LEARNDEV     = recode_factor(LEARNDEV   ,
                             "0"="NIU",
                             "1"="No",
                             "2"="Yes",
                             "7"="Unknown",
                             "8"="Unknown",
                             "9"="Unknown",
                             .ordered=T)) %>%
  mutate(STROKEV     = recode_factor(STROKEV  ,
                             "0"="NIU",
                             "1"="No",
                             "2"="Yes",
                             "7"="Unknown",
                             "8"="Unknown",
                             "9"="Unknown",
                             .ordered=T)) %>% 
  mutate(ALC5UPEVYR     = recode_factor(ALC5UPEVYR  ,
                             "0"="NIU",
                             "1"="No",
                             "2"="Yes",
                             "7"="Unknown",
                             "8"="Unknown",
                             "9"="Unknown",
                             .ordered=T)) %>% 
  mutate(ALCSTAT1       = recode_factor(ALCSTAT1    ,
                             "0"="NIU",
                             "1"="Lifetime abstainer (lt 12 drinks in life)",
                             "2"="Former drinker (no drinks past year)",
                             "3"="Current drinker (1+ drinks past year)",
                             "9"="Drinking status unknown",
                             .ordered=T)) %>% 
  mutate(PA18AERSTR     = recode_factor(PA18AERSTR  ,
                             "0"="NIU",
                             "1"="Meets neither criteria",
                             "2"="Meets strengthening criteria only",
                             "3"="Meets aerobic criteria only",
                             "4"="Meets both criteria",
                             "7"="Unknown",
                             "8"="Unknown",
                             "9"="Unknown",
                             .ordered=T)) %>% 
  mutate(SLEEPRESTFRQ      = recode_factor(SLEEPRESTFRQ  ,
                             "0"="NIU",
                             "1"="Never",
                             "2"="Some days",
                             "3"="Most days",
                             "4"="Every day",
                             "7"="Unknown",
                             "8"="Unknown",
                             "9"="Unknown",
                             .ordered=T)) %>% 
    mutate(SLEEPFALLFRQ      = recode_factor(SLEEPFALLFRQ  ,
                             "0"="NIU",
                             "1"="Never",
                             "2"="Some days",
                             "3"="Most days",
                             "4"="Every day",
                             "7"="Unknown",
                             "8"="Unknown",
                             "9"="Unknown",
                             .ordered=T)) %>% 
   mutate(SLEEPSTAYFRQ      = recode_factor(SLEEPSTAYFRQ  ,
                             "0"="NIU",
                             "1"="Never",
                             "2"="Some days",
                             "3"="Most days",
                             "4"="Every day",
                             "7"="Unknown",
                             "8"="Unknown",
                             "9"="Unknown",
                             .ordered=T)) %>% 
   mutate(SLEEPMEDFRQ      = recode_factor(SLEEPMEDFRQ  ,
                             "0"="NIU",
                             "1"="Never",
                             "2"="Some days",
                             "3"="Most days",
                             "4"="Every day",
                             "7"="Unknown",
                             "8"="Unknown",
                             "9"="Unknown",
                             .ordered=T)) %>% 
  mutate(DSOCIALP      = recode_factor(DSOCIALP  ,
                             "0"="NIU",
                             "1"="No difficulty",
                             "2"="Some difficulty",
                             "3"="A lot of difficulty",
                             "4"="Cannot do at all",
                             "7"="Unknown",
                             "8"="Unknown",
                             "9"="Unknown",
                             .ordered=T)) %>%
   mutate(WORFREQ       = recode_factor(WORFREQ   ,
                             "0"="NIU",
                             "1"="Daily",
                             "2"="Weekly",
                             "3"="Monthly",
                             "4"="A few times a year",
                             "5"="Never",
                             "7"="Unknown",
                             "8"="Unknown",
                             "9"="Unknown",
                             .ordered=T)) %>% 
  mutate(WORRX    = recode_factor(WORRX ,
                             "0"="NIU",
                             "1"="No",
                             "2"="Yes",
                             "7"="Unknown",
                             "8"="Unknown",
                             "9"="Unknown",
                             .ordered=T)) %>% 
  mutate(WORFEELEVL       = recode_factor(WORFEELEVL   ,
                             "0"="NIU",
                             "1"="A lot",
                             "2"="A little",
                             "3"="Somewhere between a lot and a little",
                             "7"="Unknown",
                             "8"="Unknown",
                             "9"="Unknown",
                             .ordered=T)) %>%
     mutate(GADANX       = recode_factor(GADANX    ,
                             "0"="Not at all",
                             "1"="Several days",
                             "2"="More than half the days",
                             "3"="Nearly every day",
                             "6"=" NIU",
                             "7"="Unknown",
                             "8"="Unknown",
                             "9"="Unknown",
                             .ordered=T)) %>% 
   mutate(DEPFREQ       = recode_factor(DEPFREQ    ,
                             "0"="NIU",
                             "1"="Daily",
                             "2"="Weekly",
                             "3"="Monthly",
                             "4"="A few times a year",
                             "5"="Never",
                             "7"="Unknown",
                             "8"="Unknown",
                             "9"="Unknown",
                             .ordered=T)) %>% 
   mutate(DEPRX     = recode_factor(DEPRX  ,
                             "0"="NIU",
                             "1"="No",
                             "2"="Yes",
                             "7"="Unknown",
                             "8"="Unknown",
                             "9"="Unknown",
                             .ordered=T)) %>% 
    mutate(DEPFEELEVL       = recode_factor(DEPFEELEVL   ,
                             "0"="NIU",
                             "1"="A little",
                             "2"="A llot",
                             "3"="Somewhere between a lot and a little",
                             "7"="Unknown",
                             "8"="Unknown",
                             "9"="Unknown",
                             .ordered=T)) %>%
  mutate(CVDDIAG     = recode_factor(CVDDIAG    ,
                             "0"="NIU",
                             "1"="No",
                             "2"="Yes",
                             "7"="Unknown",
                             "8"="Unknown",
                             "9"="Unknown",
                             .ordered=T)) %>% 
  mutate(CVDTESTRSLT    = recode_factor(CVDTESTRSLT    ,
                             "0"="NIU",
                             "1"="No",
                             "2"="Yes",
                             "3"="Did not receive test results",
                             "7"="Unknown",
                             "8"="Unknown",
                             "9"="Unknown",
                             .ordered=T)) %>% 
  mutate(CVDSYMP    = recode_factor(CVDSYMP    ,
                             "0"="NIU",
                             "1"="No symptoms",
                             "2"="Mild symptoms",
                             "3"="Moderate symptoms",
                             "4"="Severe symptoms",
                             "7"="Unknown",
                             "8"="Unknown",
                             "9"="Unknown",
                             .ordered=T)) 

```

## Write 2022 data to JSON

```{r}
write(toJSON(data_2022_recode, dataframe = 'columns'), 'NHIS_2022.json')
```
